In [3]:
import pandas as pd
import numpy as np
pd.read_excel(r'C:\Users\Lenovo\Desktop\Machine Learn excel data\Data.xlsx')

   Height  Weight  Last score  Score Grade
0     252      82          76     69     A
1     272      74          86     55     B
2     284      70          47     93     C
3     250      70          72     66     D
4     290      93          67     91     A
5     383      62          54     75     B
6     350      78          56     76     C
7     207      89          59     87     D
8     393      52          85     85     A